### ISSUE TITLE
Clarity about the source of auth token used

### ISSUE THREAD

**Issue by CodingDoug** [chiselstrike/turso-cli#271]
Right now, we have three ways of finding an auth token:

- In settings.json, from `turso auth login`
- In TURSO_API_TOKEN env var
- In `-t` CLI flag

Since all three may be present, it's potentially confusing since the CLI is not very clear about which one of these it's using when a command runs successfully.  Also, if the CLI fails because the chosen token is expired or invalid, there is no feedback about which one was problematic, leaving the user to potentially take action that doesn't resolve the issue.

Proposal:

- Let's define the order in which these sources are used. I suggest: 1. CLI flag, 2. env var, 3. settings.json
- For all (non-auth) commands that require a token, always look at all sources. If more than one token is found, immediately print a warning message listing all sources where tokens were found, and which one is being used to complete the command.

**Comment by StefanoSaffran** [comment]
Hi guys, I am opening a PR #363 trying to solve this one, I am removing the flag and adding an option to show a warning if there are multiple token sources.   
But I am not sure if it covers #270, so I did not add it in the PR.

**Comment by haaawk** [comment]
> Hi guys, I am opening a PR #363 trying to solve this one, I am removing the flag and adding an option to show a warning if there are multiple token sources. But I am not sure if it covers #270, so I did not add it in the PR.

I think we're still missing:
```
If there is a token in env, all auth commands should fail saying that auth commands aren't effective when a token is in env.
```
