### ISSUE TITLE
Add `turso tutorial` command and call it from Homebrew postinstall

### ISSUE THREAD

**Issue by penberg** [chiselstrike/turso-cli#300]
Let's have a simple `turso tutorial` command that prints basic stuff like signup, login, etc, and make the Homebrew postinstall step call that instead.

**Comment by CodingDoug** [comment]
The CLI tutorial can be found here, if the CLI wants to link to it:

https://docs.turso.tech/tutorials/get-started-turso-cli

**Comment by StefanoSaffran** [comment]
It looks like it had already been done but it didn't work and it was reverted.
https://github.com/chiselstrike/turso-cli/commit/a895b072bf4174b9484d20ab9e9eac0f49e69b07

**Comment by haaawk** [comment]
Please research what's the proper way to do it @StefanoSaffran

**Comment by haaawk** [comment]
Fixed with https://github.com/chiselstrike/turso-cli/pull/385
