### ISSUE TITLE
`turso db shell` only works from a single machine by default

### ISSUE THREAD

**Issue by penberg** [chiselstrike/turso-cli#326]
I created a database on one machine, but I am unable to access it from another machine:

```console
[penberg@turing ~]$ turso db list
NAME           LOCATIONS              URL
foo            arn (primary)          libsql://foo-penberg.turso.io
[penberg@turing ~]$ turso db shell foo
Error: failed to connect: 401 Unauthorized
```

The issue is embarrassing and obvious when you think about it: the CLI uses basic authentication credentials to login. But those credentials are only ever stored on the machine that created the database.

Suggested fix: let's automatically generate a JWT for a database on every machine the CLI is installed on and use that for `db shell`.

**Comment by penberg** [comment]
@athoscouto You fixed this, no?

**Comment by StefanoSaffran** [comment]
so, is this one done?

**Comment by penberg** [comment]
Yes, it's fixed.

**Comment by penberg** [comment]
Thanks for the reminder!
