### ISSUE TITLE
`turso account show` invocations increase "rows read" metric

### ISSUE THREAD

**Issue by penberg** [chiselstrike/turso-cli#354]
The way we probe for usage data in `turso account show` increase the rows read metric.

**Comment by haaawk** [comment]
Duplicate of https://github.com/chiselstrike/iku-turso-api/issues/382 ?

**Comment by penberg** [comment]
There's a `sqld` issue on this too: https://github.com/libsql/sqld/issues/353

**Comment by penberg** [comment]
This is fixed on the API side now.

/cc @athoscouto
