### ISSUE TITLE
Error: could not create database my-db: auth error: record not found.

### ISSUE THREAD

**Issue by rishirizz** [chiselstrike/turso-cli#374]
I tried to create a db using the command ```turso db create my-db``` but it's showing the above error. What is wrong here?

**Comment by haaawk** [comment]
Thank you for reporting @rishirizz. This seems to be an issue with organisations - our new feature. @athoscouto was the main developer of the feature. @athoscouto could you have a look please?

**Comment by rishirizz** [comment]
I restarted the terminal and gave it a go again. And guess what, it worked this time.

**Comment by haaawk** [comment]
Awesome!
