### ISSUE TITLE
Cannot drop any index

### ISSUE THREAD

**Issue by locohost** [chiselstrike/turso-cli#384]
I'm connected to my db in `turso db shell`. I'm trying drop an index an I'm getting an error.

In shell I type `DROP INDEX idx_puzzlecomment_puzzle;`, hit enter I get this error on every/any index...

`Error: Failed to execute SQL statement: DROP INDEX idx_puzzlecomment_puzzle;
unsupported statement`

I'm not sure what I"m doing wrong. I would be super happy for any advice :-)

**Comment by psarna** [comment]
@locohost sounds like a bug on our end, we need to add DROP INDEX to the list of validated and recognized statements in https://github.com/libsql/sqld/blob/86ca50d66677e325bac651a44b1dce7a41841aa1/sqld/src/query_analysis.rs#L62 ! /cc @MarinPostma @haaawk

**Comment by psarna** [comment]
ok, posted a fix, tested locally and I can drop the indexes now: https://github.com/libsql/sqld/pull/375 . Once the fix is merged and new sqld is released and uploaded to Turso, you'll be able to update the db and make DROP INDEX work 🫡
