### ISSUE TITLE
Can I change the primary's location?

### ISSUE THREAD

**Issue by 55lj** [chiselstrike/turso-cli#395]
The target market often isn't the one where the devs are. I target the US, hence I'd like to have writes happening in the US, hence my primary should be in the US, e.g. Boston.

Can I change the primary somehow? And/or could I set any location when I set up the cluster?

**Comment by CodingDoug** [comment]
It's currently not possible to change the primary once it's been allocated.  When creating a new logical database, you can [specify the location of the primary](https://docs.turso.tech/reference/turso-cli#specify-a-primary-location) using the `--location` flag.

**Comment by 55lj** [comment]
Great and thanks!
