### ISSUE TITLE
Add db export or db dump command?

### ISSUE THREAD

**Issue by ben-xD** [chiselstrike/turso-cli#433]
It would be nice to export data. Is this possible using Turso, sqld or libsql?

Thanks 🙏

**Comment by athoscouto** [comment]
You can use `turso db shell $DBNAME .dump > dump.sql` to get your database dump.
Make sure you have the latest version of the CLI installed :)
Let me know if that works for you.

**Comment by ben-xD** [comment]
Oh, I'm on the latest version (I ran `turso update`, and saw `v0.61.2`), but when running `turso db shell my_database_name .dump > dump.sql`, I get an error:
```
Error: Failed to execute SQL statement: .dump
near DOT, "None": syntax error at (1, 2)
```

**Comment by CodingDoug** [comment]
It's actually not released yet, but is committed to the repo.  If you [build from source], then run

```
```

**Comment by CodingDoug** [comment]
@ben-xD does the new dump command work for you in the latest CLI?

**Comment by ShuraimImran** [comment]
`turso db shell $DBNAME .dump > dump.sql` is not working on version 0.96.5.
