### ISSUE TITLE
Ask user if they want a replica on first `turso db create`

### ISSUE THREAD

**Issue by penberg** [chiselstrike/turso-cli#457]
To make the `turso db replicate` command discoverable, let's figure out a good location for replica and ask the user when they create their first database.

For example:

```
turso db create
Database created in Amsterdam (ams)
Would you want to create a replica in  Ashburn, Virginia (US) (iad)? (y/n)
```

**Comment by CodingDoug** [comment]
I have some constraints that I'd want to see on this:

1. Transparency about the suggestion.  What is it that makes the suggested location worthwhile?  Without context, this feels like an unwelcome upsell tactic.
2. This should only prompt if the command is being run from an interactive tty.  A prompt here would break automation scripts.
3. This suggestion should not happen if the account has reached its limit for number of databases.
