### ISSUE TITLE
Messaging for getting replica URL is out of date

### ISSUE THREAD

**Issue by CodingDoug** [chiselstrike/turso-cli#463]
```
Replicated database foo to Amsterdam, Netherlands (ams) in 11 seconds.

Client connections using libsql://... that are physically close to ams will now be routed to this replica for lower latency.

To see information about the database, including a connection URL specific to this location, run:

	turso db show foo
```

The `show` command no longer shows database URLs by default, so this message is no longer accurate.  Perhaps the trailing message should be more like this:

```
To see information about the database `foo`, run:

    turso db show foo

To see a connection URL for the new replica, run:

    turso db show foo --instance-url [name-of-replica]
```

Ideally, the generated name of the new replica is also right there in the output.  Right now we don't show the name of the new replica anywhere, and you're obliged to `show` the database first first before you can work with the new replica by name.

**Comment by glommer** [comment]
@CodingDoug btw, feel free to patch the CLI directly for stuff like this.

I'll likely have some time later today and will get to it if you don't

**Comment by glommer** [comment]
I personally find this wording slightly potentially confusing to some, and will propose:

```
To see a connection URL directly to the new replica
```

LMK

**Comment by glommer** [comment]
merged my version as is - but if you prefer a slight change on the wording I suggested lets just do it
