### ISSUE TITLE
Query plan limits from the API

### ISSUE THREAD

**Issue by penberg** [chiselstrike/turso-cli#488]
We currently have the plan limits hard-coded into the CLI. Let's add a new API for this and use that.

**Comment by Mr-Destructive** [comment]
I would like to work on this. Can I get more information? 
Like the repository where the API is built? Is it [chiselstrike](https://github.com/chiselstrike/chiselstrike)?

`v1/plans/`
This is the current api endpoint right? which gives this response
 
```json
{
  "plans": [
    {
      "name": "starter",
      "price": "0"
    },
    {
      "name": "scaler",
      "price": "29"
    }
  ]
}
```

So, need to add more fields like `max_row_reads` and  `max_row_writes`?

**Comment by penberg** [comment]
@Mr-Destructive The API server is not open source so unfortunately you won't be able to work on this until we implement the plans stuff there.

**Comment by Mr-Destructive** [comment]
Ok, cool, will look into other issues.

**Comment by athoscouto** [comment]
That is fixed on `turso plan show`. I'll close this as the new command will eventually replace `turso account show`.
