### ISSUE TITLE
Nudge users into creating picking a similar region when error happens

### ISSUE THREAD

**Issue by athoscouto** [chiselstrike/turso-cli#518]
`turso db create` and `turso db replicate` can fail because of intermittent issues in a single location.
We should nudge users into running the same command referring to a nearby location.

We can use the `v1/locations/:location` endpoint to get the 3 closest locations to a single one.
While our API doesn't have specific error codes, we can retry `503`s or even `5xx`s. 

After retrying once, if the problem still persists, we should just bail and tell them to try later.

**Comment by gris** [comment]
Do we have a dashboard or something where I can take a look at some of these errors?
