### ISSUE TITLE
`turso plan show` doesn't show the current org when it is the personal org

### ISSUE THREAD

**Issue by CodingDoug** [chiselstrike/turso-cli#544]
In order to be clear about the output, I think the org should always appear, not just for team orgs.

**Comment by avinassh** [comment]
+1 

I agree. Since an user can have different billing plan for different orgs, it’s better to show the org name as well in the output

**Comment by athoscouto** [comment]
That was intended.
The rationale is to keep the product as simple as possible for customers, only introducing complexity as necessary.


Using this case as an example, when customers sign up they only have to care about the following concepts:
- Databases
- Locations
- Instances

And they can fully use the product only thinking about those concepts.
They can even upgrade plans without knowing about organizations.

If they need to collaborate with folks, or isolate workloads, then they will need something more powerful and organizations is the next step.
But they don't need to know it, and we don't need to mention it a priori.

Having said that, this rationale is not 100% sound at this point (e.g. they may need `turso org billing`).
We can move forward with the PR that closes this issue.
When we focus on polishing the CLI experience though, I'd like us to consider moving in this "as simple as we can for as long as we can" direction.

**Comment by CodingDoug** [comment]
While I generally agree with "as simple as we can for as long as we can", that conflicted with the situation where someone *does* need an organization, and the CLI isn't obviously forthcoming about which one is currently selected. This has been a point of confusion for me as I try to navigate that scenario. So the main issue here is consistently answering the question "what org am I dealing with when I have more than a personal?". Maybe the right thing is to only show the personal org when there is more than one in play for the account, but that just seems inconsistent. @athoscouto
